### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lcsgz** [dvygolov/YellowCloaker#26]
Hello
I tried to install using DigitalOcean, and I got two errors.. ok fixed.. but now appears a new that idk how to solve this:

Fatal error: Uncaught Error: Call to undefined function get_abs_from_rel() 
in /var/www/mydomain/htdocs/htmlprocessing.php:240
 Stack trace: #0 /var/www/mydomain/htdocs/main.php(83): 
load_white_content('land', false) #1 /var/www/mydomain/htdocs/index.php(37): white(false) #2 {main} thrown in /var/www/mydomain/htdocs/htmlprocessing.php on line 240

Thank you

**Comment by dvygolov** [comment]
You somehow didn't install the cloaker correctly. So you should download it once more and copy ALL of the files to their destinations.
