### ISSUE TITLE
Blank Page when loading pages from a local folder.

### ISSUE THREAD

**Issue by GeorgesMarcel** [dvygolov/YellowCloaker#29]
Hello, I installed the Yellow Cloaker on my domain root (Hostgator cPanel). The redirect feature is working perfectly. But when I try to load white and black pages from a local folder, I get a blank page. It seems that binomo is not loading index.html files from white/black pages on local folders. Could you please help me?

![image](https://user-images.githubusercontent.com/116567638/211074943-6b2657ba-1eb4-43b8-8a49-664c873eb147.png)

**Comment by DutraMFD** [comment]
I'm having the same problem here.

I created my 2 landing pages (black and white) with elementor (wordpress). Then downloaded my 2 landing pages on HTML on https://saveweb2zip.com/en. 

So I put the folders I just downloaded in my public_html in the file manager from my website.

The redirect feature is working perfectly, but none of the pages are working. Error 404

**Comment by dvygolov** [comment]
Fixed it, download the latest version and try.
