### ISSUE TITLE
Does not display page content when Cloaker is installed in subdirectory.

### ISSUE THREAD

**Issue by AlanRicardo** [dvygolov/YellowCloaker#31]
Hello. Congratulations on the project is amazing.
I would like to confirm with you the following:
How to make cloaker work on subdirectories without redirection. Open the link slug in the same folder as the cloaker.
Example:
If the cloaker is in the "mydomain.com/offer" folder, open the offer link cloaked in that same link only on mobile.
I did several tests with Nginx and OpenLiteSpeed and the cloaker only works correctly in the root folder of the domain "mydomain.com" and does not work with cloaked links in subdirectories, it only works with redirects. When I access the cloaked link, it opens a blank page with no content.
Is it necessary to add a rewrite rule to the .htaccess file in OpenLiteSpeed and specify it in Nginx for the claker to work for the Cloaker to work correctly, camouflaging the link without redirection?

**Comment by AlanRicardo** [comment]
I did several tests again and verified that the Cloaker is really not working in Subdirectories camouflaging the link. It only works with redirects.
I manage to camouflage the slug and open the page correctly only in the root directory.
Could you explain some information about that?

**Comment by dvygolov** [comment]
Yep, it's a known issue: the cloaker does not work in subdirectories. You should place it in the root folder of your domain. I am working on this and in the new version I was able deal with it. As soon as the new version is ready it will be possible.

**Comment by AlanRicardo** [comment]
I understood.
Wow, if you manage to solve this, the tool will be perfect.
Once again...
Congratulations on the job.
