### ISSUE TITLE
"Restrict Facebook Access to an ad landing page"

### ISSUE THREAD

**Issue by DutraMFD** [dvygolov/YellowCloaker#32]
Is it possible that Facebook knows i'm using a cloaker?

- I'm using "Loading an external site via curl" option
- I deleted the BinomoCloaker.phpproj and BinomoCloaker.sln folders.

I used the same configuration for my last ad, and worked. 

Now i downloaded the lastest version and its not working. 

Maybe i'm doing something wrong?

**Comment by dvygolov** [comment]
What do you mean by "its not working"?

**Comment by DutraMFD** [comment]
Facebook knows that i'm using a cloaker: "Restrict Facebook Access to an ad landing page"

My ad was not aproved.

**Comment by dvygolov** [comment]
Just don't use CURL for the safe page, use a local one from folder. And all
will be ok
