### ISSUE TITLE
FB Pixel doubts/questions

### ISSUE THREAD

**Issue by edgmin** [dvygolov/YellowCloaker#34]
Hello, 

First of all, I would like to thank you for the cloaker! I works just awesome and has been very useful!

I would like to get your opinion/suggestion about the following:

I am using your cloaker in my sales page which contains a video sales letter (VSL). This is an intermediate page though, as the lead is redirected after watching the VSL (after clicking on a button) to the checkout page of another website (similar to shopify). This is somehow different from the cloaker setup you have here where, if I understood  correctly, is intended to capture leads/ purchases in your own webpage itself.

My concern here is about the facebook pixel. As far as I understood, after capturing the lead/purchase, you fire the pixel back to facebook. In my case, as I am not using the "thankyou" page and so on, I have not added any pixel to my VSL website... only to my checkout (which is in another website - where I optimize facebook pixel for conversion). I would like to ask you how the pixel stuff/functions works in the following cases:

1) When I set the cloaker to redirect from my white page to the black page, does the cloaker fire the Pixel event of "PageView" as if the pixel were installed on the white page? or does it fire directly from the black page? My concern here is that FB sees that the pixel is being fired from another page other than the one it was set to send users (different URL) (that's why I did not put my pixel on my black pages - as it would also only tell about 'PageView' and I am optimizing my campaigns for conversion instead. Do you mind sharing how it exactly works? Any suggestion here is highly appreciated!

2) If I still want to fire the 'PageView' for my black page. Could you point me to the function that gets called to fire the FB pixel? So far I understood how you get the fb pixel id number from the url and stores it in a cookie or in a form.. The part that I do not understand is where (in which webpage) you fire the 'PageView' event to fb once you collect it in the black page.. Can I get the pixel id number from the url link and directly put the code to fire the 'PageView' in the black page itself? Or in this way fb will know my black page? Could you share how you do it?

**Comment by dvygolov** [comment]
Hello, and sorry for a long wait.
You can just use a local VSL as a prelanding and a redirect for you offer.

About your questions:

1. The pixel fires PageView only if you tell it to do so. There is a setting for that. If you don't need PageView just don't use it. BTW, pixel that fires from the page who's domain differs from the one that you put in your Facebook ad, is not a very big deal, I ran many campaigns that did so. 

You should use a redirect for your checkout page and there you should manually add your pixel. 

2. Yep, you can do the job of firing the pixel manually if you want.

**Comment by opencbct** [comment]
Thank you, Daniel. Nice work ^^.

Benjamin Kim
M. 224-600-2727
<https://opencbct.com>
https://<https://GuideDoc.io>GuideDoc.io
https://RentalXray.com

[signatureImage]
________________________________

**Comment by quesups** [comment]
Здравствуйте, у меня проблемы с установкой желтого плаща, я следовал инструкциям, которые вы предоставили, но все равно получаю сообщение об ошибке. Надеюсь, вы мне поможете, жду ответа.

**Comment by dvygolov** [comment]
Hello, first of all it is better to write in english, cause russian
auto-translate is bad. Second: where is a screenshot or a description of
your error? Should I somehow make guesses? Please, don't waste my time and
tell me all the details right away.

**Comment by dvygolov** [comment]
you should copy-paste the cloaker's files into the root folder of your
domain
