### ISSUE TITLE
Cloaker::$detect is deprecated 

### ISSUE THREAD

**Issue by Rubyx-code** [dvygolov/YellowCloaker#35]
Hi,

Thank you for the script!

Why I'm getting on error on the 404 page:

Deprecated: Creation of dynamic property Cloaker::$detect is deprecated in /YellowCloaker-master/core.php on line 68

How to fix it?

**Comment by Rubyx-code** [comment]
I fixed it.

I changed PHP8 to PHP7

**Comment by rodeg83** [comment]
Hi.. How u do man? Changed where?

**Comment by Rubyx-code** [comment]
> Hi.. How u do man? Changed where?

Server PHP version
