### ISSUE TITLE
Using Beget

### ISSUE THREAD

**Issue by Shimalay9** [dvygolov/YellowCloaker#40]
Hi

Using the cloaker on a beget VPS. Its not responding at all under any modes(site/redirect/curl/error). Infact its throwing error if none of Lead/Purchase/Reject/Trash are selected in point 9. None responsive script. Let me know if you need any additional details to resolve this. It was throwing an error when executed on default permissions, so changed all directory/files permissions to 777. Tried across PHP 7.4/8.0/8.1/8.2.

Regards

**Comment by dvygolov** [comment]
> Infact its throwing error if none of Lead/Purchase/Reject/Trash are selected in point 9.
Fixed that, thank you.
