### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SleekDB\Exceptions\IOException' not found in

### ISSUE THREAD

**Issue by domodigitalbusiness** [dvygolov/YellowCloaker#42]
![Screenshot (14)](https://github.com/user-attachments/assets/f194103f-4909-4810-a91e-9c51c33f9195)

**Comment by domodigitalbusiness** [comment]
Im using your cloaker for a while and its helping me a lot! But today i woke up with loss ad spent because it got this error. What to do when this happend? How to fix it fast?

**Comment by krishnamaurya-96** [comment]
Have you check your php version?

**Comment by domodigitalbusiness** [comment]
No, what version it needs to be?

**Comment by krishnamaurya-96** [comment]
If not working on php8 then select php7.4 version.

**Comment by dvygolov** [comment]
> Im using your cloaker for a while and its helping me a lot! But today i woke up with loss ad spent because it got this error. What to do when this happend? How to fix it fast?

Fixed that in the latest release, now it will show you the actual error.
