### ISSUE TITLE
How can I preserve my URL parameters when redirecting to another site?

### ISSUE THREAD

**Issue by lariguedes98** [dvygolov/YellowCloaker#47]
Hello, I need to preserve the utm parameters of the URL when redirecting to another site.

Example:

My cloaker is at: https://mydomain.com/cloaker

When clicking on the ad, the user will have a URL similar to this: https://mydomain.com/cloaker?utm_source=fbads&utm_term=instagram_feed

On the black page, my cloaker is configured to be redirected to this site: https://myotherdomain.com

I would like the user to arrive at the second site with the parameters of the first domain, would it be possible to do this? How?

In the user's browser it would look like this: https://myotherdomain.com?utm_source=fbads&utm_term=instagram_feed

![image](https://github.com/user-attachments/assets/9548d08f-57d3-4f53-90d1-3b3cebd164b4)

**Comment by dvygolov** [comment]
As far as I remember you should use macros in the redirect link. So you
should redirect to:

https://myotherdomain.com?utm_source={utm_source}&utm_term={utm_term}

You should be able to use any parameter from the original request link
using {}

Try it and let me know if it works.

**Comment by lariguedes98** [comment]
At first, just putting the parameters as you indicated, it didn't work, but checking the option shown in the image, it worked perfectly. Thanks, Daniel!!

![image](https://github.com/user-attachments/assets/af8f72f4-567c-47ec-ac19-2192bd82d0c3)
