### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/site/requestfunc.php:54 Stack trace: #0 /var/www/site/htmlprocessing.php(81): get_html() #1 /var/www/site/main.php(133): load_landing() #2 /var/www/site/index.php(32): black() #3 {main} thrown in /var/www/site/requestfunc.php on line 54

### ISSUE THREAD

**Issue by carminaagilar504** [dvygolov/YellowCloaker#51]
Local landing page:

Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/site/requestfunc.php:54 Stack trace: #0 /var/www/site/htmlprocessing.php(81): get_html() #1 /var/www/site/main.php(133): load_landing() #2 /var/www/site/index.php(32): black() #3 {main} thrown in /var/www/site/requestfunc.php on line 54

**Comment by dvygolov** [comment]
Hello, you don't have CURL installed on your server.

**Comment by carminaagilar504** [comment]
apt install curl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1ubuntu1.18).
curl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

**Comment by carminaagilar504** [comment]
thanks
1. `apt-get install php-curl`
2. `service apache2 restart`
